### ISSUE TITLE
Need npm for phoenix v0.10.0

### ISSUE THREAD

**Issue by ijt** [trenpixster/elixir-dockerfile#6]
Phoenix depends on nodejs now for brunch. It can be installed with these lines:

RUN     curl -sL https://deb.nodesource.com/setup | sudo bash -
RUN     apt-get install -y nodejs

**Comment by trenpixster** [comment]
Thanks for the suggestion! Although I believe the normal use cas is to indeed use Phoenix, I think adding nodejs steps a bit out of context for an "Elixir Dockerfile" :smile:

**Comment by ijt** [comment]
Oh, of course. I should make a fork.
